version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: scheduler_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: task_scheduler
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/
    networks:
      - scheduler_network

  kafka:
    image: bitnami/kafka:3.5
    container_name: scheduler_kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    networks:
      - scheduler_network

  redis:
    image: redis:7-alpine
    container_name: scheduler_cache
    ports:
      - "6379:6379"
    networks:
      - scheduler_network

networks:
  scheduler_network:
    driver: bridge

volumes:
  postgres_data:
